### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by timeshift79** [ComputerGhost/FaviconFetcher#5] opened 2022-03-29 14:51 UTC
Not able to get favicon from the following site:

https://ice-sentralbord.ice.no/

I collects the favicon with the scanner, but it doesn't extract the link:

![image](https://user-images.githubusercontent.com/56876167/160639900-c11abb58-975d-4254-b3ca-f9f9861f0a2c.png)

The url for the favicon is "https://sentralbord.ice.no/app/res/favicon.ico", but the scanner finds "https://ice-sentralbord.ice.no/res/favicon.ico".

**Comment by ComputerGhost** [comment] 2022-04-03 03:20
Problem fixed in latest version 1.3.0.  Now the base tag is supported, which fixes the favicon url for your example.

**Comment by timeshift79** [comment] 2022-04-03 13:06
Thanks, but did you break support for .net framework?

![image](https://user-images.githubusercontent.com/56876167/161429595-9b982bfd-0471-493f-b57e-fd99bfaefcd7.png)

**Comment by ComputerGhost** [comment] 2022-04-03 16:48
Thanks for pointing this out!  It should be fixed now, version 1.3.1.  I added support back for netstandard2.0.

**Closed as completed by ComputerGhost** 2022-04-03 16:48 UTC

**Comment by timeshift79** [comment] 2022-04-04 06:20
Thanks, working again now. Another small issue that appeared is that if you fetch the closest:

`var image = fetcher.FetchClosest(uri, new Size(48, 48));`

It doesn't return any image, even though it finds one with the scanner. The logic of the function should be that it fetches the closest, and if the closest is eg 16x16 or anything else, it should return that. For the above mentioned link it doesn't return anything using the FetchClosest.

**Comment by timeshift79** [comment] 2022-04-05 10:00
It still doesn't get the correct url if you try the first link i posted in this issue.

**Comment by ComputerGhost** [comment] 2022-04-05 15:35
I'll make a new issue later for the fetcher not pulling it down.  The original issue was because the "base" tag was being ignored.  Adding support for that fixed the scanner URLs.  This new problem with the fetcher is caused by a 'text/html' content type being used for the icon.
